# Generated by Django 3.0.8 on 2020-09-07 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_image_link', models.CharField(max_length=200)),
                ('chairperson_image_link', models.CharField(max_length=200)),
                ('about_IIIT_Dharwad', models.CharField(max_length=3000)),
                ('chairperson_message', models.CharField(max_length=3000)),
                ('director_message', models.CharField(max_length=3000)),
                ('about_IIIT_Dharwad_hindi', models.CharField(max_length=3000)),
                ('chairperson_message_hindi', models.CharField(max_length=3000)),
                ('director_message_hindi', models.CharField(max_length=3000)),
                ('about_IIIT_Dharwad_kannada', models.CharField(max_length=3000)),
                ('chairperson_message_kannada', models.CharField(max_length=3000)),
                ('director_message_kannada', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='AboutUsTestimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_link', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('name_hindi', models.CharField(max_length=50)),
                ('position_hindi', models.CharField(max_length=50)),
                ('description_hindi', models.CharField(max_length=300)),
                ('name_kannada', models.CharField(max_length=50)),
                ('position_kannada', models.CharField(max_length=50)),
                ('description_kannada', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='AcademicCalLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acad_link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Academics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cse_image_link', models.CharField(max_length=200)),
                ('ece_image_link', models.CharField(max_length=200)),
                ('academic_calendar_link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AcademicsCSE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=3000)),
                ('description_hindi', models.CharField(max_length=3000)),
                ('description_kannada', models.CharField(max_length=3000)),
                ('academic_calendar_link', models.CharField(max_length=200)),
                ('curriculum_link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AcademicsECE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=3000)),
                ('description_hindi', models.CharField(max_length=3000)),
                ('description_kannada', models.CharField(max_length=3000)),
                ('academic_calendar_link', models.CharField(max_length=200)),
                ('curriculum_link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CampusPageDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_hindi', models.CharField(max_length=100)),
                ('title_kannada', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=3000)),
                ('description_hindi', models.CharField(max_length=3000)),
                ('description_kannada', models.CharField(max_length=3000)),
                ('image_link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CurriculumLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cse_link', models.CharField(max_length=200)),
                ('ece_link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_name_hindi', models.CharField(max_length=100)),
                ('event_name_kannada', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=1000)),
                ('description_hindi', models.CharField(max_length=1000)),
                ('description_kannada', models.CharField(max_length=1000)),
                ('image_link', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyPageInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_hindi', models.CharField(max_length=100)),
                ('name_kannada', models.CharField(max_length=100)),
                ('phd_info', models.CharField(max_length=100)),
                ('phd_info_hindi', models.CharField(max_length=100)),
                ('phd_info_kannada', models.CharField(max_length=100)),
                ('teaching_position', models.CharField(max_length=300)),
                ('teaching_position_hindi', models.CharField(max_length=300)),
                ('teaching_position_kannada', models.CharField(max_length=300)),
                ('linkedin_link', models.CharField(max_length=300)),
                ('email_id', models.CharField(max_length=100)),
                ('image_link', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='HomePageUpcomingEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=1000)),
                ('description_hindi', models.CharField(max_length=1000)),
                ('description_kannada', models.CharField(max_length=1000)),
                ('location', models.CharField(max_length=100)),
                ('image_link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NewsLetterEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NewsPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_name', models.CharField(max_length=100)),
                ('image_link', models.CharField(max_length=200)),
                ('headline', models.CharField(max_length=300)),
                ('headline_hindi', models.CharField(max_length=300)),
                ('headline_kannada', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=3000)),
                ('description_hindi', models.CharField(max_length=3000)),
                ('description_kannada', models.CharField(max_length=3000)),
                ('news_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OurFamilyLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_hindi', models.CharField(max_length=50)),
                ('name_kannada', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Placements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_link', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=300)),
                ('point_hindi', models.CharField(max_length=300)),
                ('point_kannada', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchStudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_hindi', models.CharField(max_length=100)),
                ('name_kannada', models.CharField(max_length=100)),
                ('image_link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_link', models.CharField(max_length=500)),
                ('image_name', models.CharField(max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iiitdsite.Events')),
            ],
        ),
        migrations.CreateModel(
            name='CampusPageGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_link', models.CharField(max_length=200)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iiitdsite.CampusPageDetails')),
            ],
        ),
    ]
