# Generated by Django 3.0.8 on 2020-09-07 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdsite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepageupcomingevents',
            name='image_link',
        ),
    ]
