# Generated by Django 3.0.8 on 2020-09-07 06:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdsite', '0002_remove_homepageupcomingevents_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageupcomingevents',
            name='image_link',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
