# Generated by Django 3.0.8 on 2020-09-08 05:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdsite', '0004_administration_bog_financecommittee_senate_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourfamilylink',
            name='link_hindi',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ourfamilylink',
            name='link_kannada',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
