# Generated by Django 3.0.8 on 2020-09-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdsite', '0005_auto_20200908_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOGMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_hindi', models.CharField(max_length=100)),
                ('name_kannada', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=300)),
                ('position_hindi', models.CharField(max_length=300)),
                ('position_kannada', models.CharField(max_length=300)),
                ('image_link', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='BOGNonMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_hindi', models.CharField(max_length=100)),
                ('name_kannada', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=300)),
                ('position_hindi', models.CharField(max_length=300)),
                ('position_kannada', models.CharField(max_length=300)),
                ('image_link', models.CharField(max_length=300)),
            ],
        ),
        migrations.RenameModel(
            old_name='BOG',
            new_name='BOGChairperson',
        ),
    ]
