# Generated by Django 3.0.8 on 2020-09-08 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdsite', '0006_auto_20200908_1130'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FinanceCommittee',
            new_name='FinanceCommitteeMembers',
        ),
    ]
