# Generated by Django 3.0.8 on 2020-09-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdsite', '0009_auto_20200908_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='phdlinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertisement', models.CharField(max_length=200)),
                ('click_here_to_apply', models.CharField(max_length=200)),
                ('fee_structure', models.CharField(max_length=200)),
                ('sbi_collect', models.CharField(max_length=200)),
                ('instructions_sbi_collect', models.CharField(max_length=200)),
                ('academic_regulations', models.CharField(max_length=200)),
                ('scholarships_bank_loans', models.CharField(max_length=200)),
                ('policy', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ugcselinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jossa_link', models.CharField(max_length=200)),
                ('csab_link', models.CharField(max_length=200)),
                ('course_seat_matrix', models.CharField(max_length=200)),
                ('admission_checklist', models.CharField(max_length=200)),
                ('fee_structure', models.CharField(max_length=200)),
                ('sbi_collect', models.CharField(max_length=200)),
                ('instructions_sbi_collect', models.CharField(max_length=200)),
                ('academic_regulations', models.CharField(max_length=200)),
                ('scholarships_bank_loans', models.CharField(max_length=200)),
                ('policy', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ugecelinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jossa_link', models.CharField(max_length=200)),
                ('csab_link', models.CharField(max_length=200)),
                ('course_seat_matrix', models.CharField(max_length=200)),
                ('admission_checklist', models.CharField(max_length=200)),
                ('fee_structure', models.CharField(max_length=200)),
                ('sbi_collect', models.CharField(max_length=200)),
                ('instructions_sbi_collect', models.CharField(max_length=200)),
                ('academic_regulations', models.CharField(max_length=200)),
                ('scholarships_bank_loans', models.CharField(max_length=200)),
                ('policy', models.CharField(max_length=200)),
            ],
        ),
    ]
