# Generated by Django 3.0.8 on 2020-09-08 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdsite', '0010_phdlinks_ugcselinks_ugecelinks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ugecelinks',
        ),
    ]
