# Generated by Django 3.0.8 on 2020-09-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdsite', '0011_delete_ugecelinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatiiitd', models.CharField(max_length=3000)),
                ('whyiiitd', models.CharField(max_length=3000)),
                ('faculty', models.CharField(max_length=5000)),
                ('innovations', models.CharField(max_length=7000)),
                ('location', models.CharField(max_length=7000)),
                ('permcampus', models.CharField(max_length=5000)),
                ('queries', models.CharField(max_length=3000)),
            ],
        ),
    ]
