# Generated by Django 3.0.8 on 2020-09-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdsite', '0012_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_loan_application', models.CharField(max_length=200)),
                ('checklist', models.CharField(max_length=200)),
            ],
        ),
    ]
