# Generated by Django 3.0.8 on 2020-09-11 05:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdsite', '0014_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='news_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
