# Generated by Django 3.0.8 on 2020-09-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdsite', '0015_alert_news_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_link', models.CharField(max_length=200)),
                ('asso_prof_link', models.CharField(max_length=200)),
                ('assi_prof_link', models.CharField(max_length=200)),
                ('project', models.CharField(max_length=200)),
                ('tech_assistant', models.CharField(max_length=200)),
                ('assi_registrar', models.CharField(max_length=200)),
                ('super_hrm', models.CharField(max_length=200)),
                ('super_accounts', models.CharField(max_length=200)),
                ('office_assistant', models.CharField(max_length=200)),
                ('audit_officer', models.CharField(max_length=200)),
            ],
        ),
    ]
