# Generated by Django 3.0.8 on 2020-09-12 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdsite', '0018_auto_20200912_2043'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='jhobs',
            new_name='Jobs',
        ),
    ]
