# Generated by Django 3.0.8 on 2020-09-18 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdsite', '0019_auto_20200912_2043'),
    ]

    operations = [
        migrations.DeleteModel(
            name='faq',
        ),
        migrations.RemoveField(
            model_name='about',
            name='about_IIIT_Dharwad',
        ),
        migrations.RemoveField(
            model_name='about',
            name='about_IIIT_Dharwad_hindi',
        ),
        migrations.RemoveField(
            model_name='about',
            name='about_IIIT_Dharwad_kannada',
        ),
        migrations.RemoveField(
            model_name='about',
            name='chairperson_message',
        ),
        migrations.RemoveField(
            model_name='about',
            name='chairperson_message_hindi',
        ),
        migrations.RemoveField(
            model_name='about',
            name='chairperson_message_kannada',
        ),
        migrations.RemoveField(
            model_name='about',
            name='director_message',
        ),
        migrations.RemoveField(
            model_name='about',
            name='director_message_hindi',
        ),
        migrations.RemoveField(
            model_name='about',
            name='director_message_kannada',
        ),
    ]
