# Generated by Django 3.0.8 on 2020-09-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdsite', '0021_auto_20200928_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.ImageField(blank=True, upload_to='EventsCover/%Y/%m/%d'),
        ),
    ]
