# Generated by Django 3.0.8 on 2020-10-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdsite', '0024_auto_20200928_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutustestimonial',
            name='image_link',
        ),
        migrations.RemoveField(
            model_name='administration',
            name='image_link',
        ),
        migrations.RemoveField(
            model_name='bogchairperson',
            name='image_link',
        ),
        migrations.RemoveField(
            model_name='bogmembers',
            name='image_link',
        ),
        migrations.RemoveField(
            model_name='bognonmembers',
            name='image_link',
        ),
        migrations.RemoveField(
            model_name='campuspagedetails',
            name='image_link',
        ),
        migrations.RemoveField(
            model_name='campuspagegallery',
            name='image_link',
        ),
        migrations.RemoveField(
            model_name='facultypageinfo',
            name='image_link',
        ),
        migrations.RemoveField(
            model_name='financecommitteemembers',
            name='image_link',
        ),
        migrations.RemoveField(
            model_name='homepagegallery',
            name='image_link',
        ),
        migrations.RemoveField(
            model_name='homepageupcomingevents',
            name='image_link',
        ),
        migrations.RemoveField(
            model_name='images',
            name='image_link',
        ),
        migrations.RemoveField(
            model_name='newspage',
            name='image_link',
        ),
        migrations.RemoveField(
            model_name='placements',
            name='logo_link',
        ),
        migrations.RemoveField(
            model_name='senatechairperson',
            name='image_link',
        ),
        migrations.RemoveField(
            model_name='senatemembers',
            name='image_link',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='image_link',
        ),
        migrations.AddField(
            model_name='aboutustestimonial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='About/'),
        ),
        migrations.AddField(
            model_name='administration',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Administration/'),
        ),
        migrations.AddField(
            model_name='bogchairperson',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Chairperson/'),
        ),
        migrations.AddField(
            model_name='bogmembers',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='BOGMembers/'),
        ),
        migrations.AddField(
            model_name='bognonmembers',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='BOGNonMembers'),
        ),
        migrations.AddField(
            model_name='campuspagedetails',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Campus/'),
        ),
        migrations.AddField(
            model_name='campuspagegallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='CampusGallery/'),
        ),
        migrations.AddField(
            model_name='facultypageinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Faculty/'),
        ),
        migrations.AddField(
            model_name='financecommitteemembers',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='FCMembers/'),
        ),
        migrations.AddField(
            model_name='homepagegallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Events/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='homepageupcomingevents',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='UpcomingEventsCover/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Events/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='News/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='placements',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='PlacementCompanyLogo/'),
        ),
        migrations.AddField(
            model_name='senatechairperson',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Chairperson'),
        ),
        migrations.AddField(
            model_name='senatemembers',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='SenateMembers/'),
        ),
        migrations.AddField(
            model_name='staff',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Staff/'),
        ),
        migrations.AlterField(
            model_name='about',
            name='chairperson_image_link',
            field=models.ImageField(blank=True, null=True, upload_to='Chairperson/'),
        ),
        migrations.AlterField(
            model_name='about',
            name='director_image_link',
            field=models.ImageField(blank=True, null=True, upload_to='Director/'),
        ),
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='EventsCover/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='researchstudents',
            name='image_link',
            field=models.ImageField(blank=True, null=True, upload_to='ResearchStudents/'),
        ),
    ]
